baseurl      = "/"
title        = "Jaiz Jeeson's Personal Website"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "02/01/2006"
  dateformNumTime = "02/01/2006 15:04"

  # Paths to custom CSS and JS files.
  customCSS = ["/css/style.css"]
  customJS  = ["/js/Home.js"]

  # Subtitle for home
  homeSubtitle = "CS undergrad | Professional Daydreamer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  backgroundImage = ""

  # Metadata mostly used in document's head
  description = "Jaiz's personal website."
  keywords = ""
  images = [""]

  # Colors for favicons
  #
  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoMark     = ">"
    logoText     = "$ /home/"
    logoHomeLink = "/"
    # Set true to remove the logo cursor entirely.
    logoCursorDisabled = false
    # Set to a valid CSS color to change the cursor in the logo.
    # logoCursorColor    = "#67a2c9"
    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    # logoCursorAnimate  = "2s"
    # Append the current url pathname to logoText 
    logoCursorPathname = true

  # Social icons
  [[params.social]]
  name = "email"
  url = "jaizepic@gmail.com"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/jaiz-jeeson-8b388b1b2/"
  
  [[params.social]]
    name = "github"
    url = "https://github.com/Jaiz183"

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Jaiz Jeeson"
    subtitle = "Personal Website"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  # Add menus here!
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts/"

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/categories/projects/"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/"
  