baseurl      = "/"
title        = "Jaiz Jeeson's Personal Website"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Paths to custom CSS files.
  customCSS = ["/css/style.css"]

  # Subtitle for home
  homeSubtitle = "CS undergrad and professional daydreamer."

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Enable sharing buttons, if you like
  enableSharingButtons = false
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "Jaiz's personal website."
  keywords = ""
  images = [""]

  # Social icons
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/jaiz-jeeson-8b388b1b2/"
  
  [[params.social]]
    name = "github"
    url = "https://github.com/Jaiz183"
  
  [[params.social]]
    name = "email"
    url = "jaizepic@gmail.com"
  
  [[params.social]]
    name = "anilist"
    url = "https://anilist.co/activity/612870322"

[taxonomies]
    category = "categories"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Jaiz Jeeson"
    subtitle = "Personal Website"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "cd ~"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # Add menus here!
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/categories/projects"
  